#!/usr/bin/env bash
# Transfers a file to a server using scp

# Check if exactly 4 parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file to the user's home directory (~/) using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/